# Generated by Django 2.1.7 on 2019-05-15 08:18

import config.helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('random_report_id', models.CharField(default=config.helper.random_id, editable=False, max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Random Report Id')),
                ('message', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='random_comment_id',
            field=models.CharField(default=config.helper.random_id, editable=False, max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Random Comment Id'),
        ),
    ]
